#%RAML 1.0
title: Yumee API
baseUri: http://api.yumee.ru

types:
  phone_example:
    description: Номер телефона в любом формате
    required: true
    examples:
      1:
        value: '79205556789'
      2:
        value: '(920) 555-67-89'

/verify:
  displayName: Подтвердить телефон
  description: |
    Отправить на указанный <code>phone</code> СМС-код для подтверждения номера телефона.
    Статус <code>200 OK</code> в случае успешной отправки кода.
    Повторный запрос возможен через 2 минуты.
  post:
    queryParameters:
      phone: phone_example
    responses:
      200:
        description: Код отправлен
      422:
        description: Неверный номер телефона
        body:
          application/json:
            example:
              error: wrong number
/token:
  displayName: Авторизация
  description: |
    Получить JSON WEB TOKEN для авторизации запросов.
    Возвращает <code>404 NOT FOUND</code>, если введён неверный код
    подтверждения и <code>201 CREATED</code> в случае успешной генерации
    токена. Если пользователя с переданным <code>phone</code> ещё
    не существует, то он будет создан автоматически.
    <p style='color: #f92672; margin-top: 20px'>
      Далее, для авторизации запросов полученный JWT-токен необходимо включать в заголовок:<br>
      <code>Authorization: {{ JWT_TOKEN }}</code>
    </p>
  post:
    queryParameters:
      auth[phone]: phone_example
      auth[code]:
        description: |
          4-х занчный код подтверждения, высланный по СМС на <code>phone</code>
          методом <code>/verify</code>
        required: true
        examples:
          1:
            value: '1234'
    responses:
      201:
        description: JWT успешно сгенерирован
        body:
          application/json:
            example:
              jwt: eyJ0eXAiOqJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjJ9.iKJk6o6Z6aAIEiF_e4nXyXSVM-3Mg1y9o-EnCu-Dq5s
      404:
        description: Неверный код подтверждения
/plans:
  displayName: Тарифные планы
  description: Получить список тарифных планов
  get:
    responses:
      200:
        body:
          application/json:
            example:
              [
                {
                    "id": 1,
                    "title": "Похудеть",
                    "description": "Кол-во каллорий меньше суточной нормы",
                    "logo": logo_1.png
                },
                {
                    "id": 2,
                    "title": "Быть в форме",
                    "description": "Кол-во каллорий равно суточной норме",
                    "logo": logo_2.png
                },
                {
                    "id": 3,
                    "title": "Быть в форме",
                    "description": "Кол-во каллорий больше суточной нормы",
                    "logo": logo_2.png
                }
            ]
/profile:
  displayName: Профиль
  description: Получение и обновление данных текущего (залогиненного) профиля
  get:
    description: Получить информацию о текущем профиле
    responses:
      200:
        body:
          application/json:
            example:
              {
                "name": "Берестовой Андрей",
                "phone": "79205556789",
                "preferences": [1, 5],
                "age": 25,
                "height": 175,
                "weight": 60,
                "plan": {
                    "id": 2,
                    "title": "Быть в форме",
                    "description": "Кол-во каллорий равно суточной норме",
                    "logo": logo_2.png
                },
                "address": {
                    "id": 7,
                    "street": "ул. Тверская",
                    "building": 105,
                    "corpus": 2,
                    "floor": 9,
                    "flat": 170,
                    "stroenie": null,
                    "domofon": 170K8877,
                    "comment": Звонок на этаже не работает,
                    "lat": null,
                    "lng": null,
                    "city_id": 1
                }
            }
  put:
    description: Обновить текущий профиль
    queryParameters:
      name:
        required: false
        description: Имя
        example: Берестовой Андрей
      preferences:
        required: false
        description: |
          Предпочтения по графику питания:<br>
          <p>
            <span style='display: block'>1. Завтрак</span>
            <span style='display: block'>2. Обед</span>
            <span style='display: block'>3. Полдник</span>
            <span style='display: block'>4. Десерт</span>
            <span style='display: block'>5. Ужин</span>
          </p>
        type: array
        example: [1, 5]
      age:
        required: false
        description: Возраст
        type: integer
        example: 25
      height:
        required: false
        description: Рост
        type: integer
        example: 180
      weight:
        required: false
        description: Вес
        # type: float @todo: разобраться
        example: '65.2'
      plan_id:
        required: false
        description: ID тарифного плана (см. <a href='#тарифные-планы'>тарифные планы</a>)
        type: integer
        example: 3
      address[street]:
        required: false
        description: Улица
        example: ул. Тверская
      address[building]:
        required: false
        description: Дом
        example: '1'
      address[corpus]:
        required: false
        description: Корпус
        example: '5'
      address[stroenie]:
        required: false
        description: Строение
        example: '1'
      address[domofon]:
        required: false
        description: Код домофона
        example: 170K8877
      address[comment]:
        required: false
        description: Комментарий к адресу
        example: Звонок на этаже не работает
      address[lat]:
        required: false
        description: Широта
        example: '55.7558'
      address[lng]:
        required: false
        description: Долгота
        example: '37.6173'