#%RAML 1.0
title: Yumee API
version: v1
baseUri: http://api.yumee.com
/users:
  post:
  get:
    body:
      application/json:
    responses:
      200:
        body:
          application/json:
            type: array

